README.MD

Markdown changes

---

README.MD

Correct capitalisation of JavaScript

Correct capitalisation of JavaScript

---

README.MD

Code example of pure SCSS (CSS) mouse tracking with a possibility to change tracking sensitivity.

Added example of pure CSS Mouse tracking

---

README.MD
convert/styles.css

Reverts NamPNQ/You-Dont-Need-Javascript#28

Revert "Clean up"

---

README.MD

- Highlights todos that have changed.
- Shows number of changed todos.
- Shows number of completed todos.
- Disables the "Save" button if none of the todos' are changed.
- Includes fallback styles for browsers that lack support for the neighbor/sibling ` ~ ` and `:checked` selectors.
You can't create new todos or edit/delete existing ones, but it's possible to add CSS-enhanced versions of those features.

Added example of a basic CSS-only todo list

---

README.MD

Hi there,
these demos are really interesting from a CSS Proof of Concept or technical point of view, but are a real nonsense from accessibility point of view.
Please mention it before it comes to production and create problems for people who need accessible solutions.
Kind regards,
Nicolas

Mention of accessibility issues of these demos

---

README.MD

Link to demo a menu mobile off canvas with a sexy effect

Add mobile menu off canvas

---

README.MD

Signed-off-by: shaishavgandhi05 <shaishgandhi@gmail.com>

Added example for pure CSS Image Gallery

---

README.MD

https://codepen.io/anon/pen/eZWXOZ

Counter of checked check-boxes

---

examples/image-gallery-1.html

#29 
Signed-off-by: shaishavgandhi05 <shaishgandhi@gmail.com>

Added HTML files for Image Gallery

---

examples/checkbox-counter.html
examples/game-1.html
examples/game-2.html
examples/modal-1.html
examples/modal-2.html
examples/mouse-tracking.html

Signed-off-by: shaishavgandhi05 <shaishgandhi@gmail.com>

Added all other HTML files

---

README.MD

Add demo for creating tooltips using only CSS.

add tooltip section

---

examples/loader-1.html
examples/loader-2.html
examples/loader-3.html
examples/loader-4.html
examples/loader-5.html
examples/loader-6.html
examples/loader-7.html
examples/loader-8.html
examples/loader-9.html

Signed-off-by: shaishavgandhi05 <shaishgandhi@gmail.com>

Added Loader HTMLs

---

README.MD

Add quick links

---

README.MD

change contribute text

---

README.MD

I have fixed path to image for "Info on hover/ Popover" section

fix image path

---

README.MD

Neither game example is functional.
The first game relies on 3rd party domain assets that are no longer available.
The sudoku example doesn't initialize the puzzle.

Remove Games

---

README.MD

oh! let's create spectrum page.

(chore):Add spectrum chat

---

README.MD
examples/neon-button.html

Please add the hacktoberfest tag
Thank You

Add Neon button

---

examples/css-toggle-modal.html

A `checkbox` based **toggle modal**.

Added Pure CSS Toggle Modal

---

examples/art.html

Find a pure CSS art and check out my other arts on codepen.io/KandarpSolanki

Added art.html containing pure CSS art

---

examples/flip-2.html

I really liked the card flip feature and thought a side to side flip feature would be fun as well!

added side to side feature to extend card flip

---

README-zh_CN.md

Fix link in the README-zh_CN.md otherwise we will get 404

docs: fix link in README-zh_CN.md

---

examples/floating-labels-1.html
examples/image-gallery-1.html

This pull request includes several changes and modifications to enhance the UI and styling of the website. Here's a breakdown of the changes:
In the CSS:
In the .wrapper class, reduced margin-top to 80px for better spacing.
In the .material-textfield class, increased height to 6rem and set position to static to adjust the element's height and position it without any offset. Added align-items: center; for centering the content vertically.
Introduction of New CSS:
Added new CSS rules to style a button box with a gradient background, a border, box shadow, and a hover effect.
Created a .box class to style an overlaying box with a red outline and a transparent interior.
HTML Modification:
Added a new div with the class .button-box to create a submit button within the .wrapper.
This button is …

Update UI and Styling

---

README.MD

Remove an extra bracket which is blocking user from viewing the neon button animation example

[Issue #132] Fix link in Neon button Animation demo

---

README.MD

Fixes #7 
Allow newlines in info hovers

[Issue #7] Allow newlines in info hovers

---

examples/todo-1.html

This pull request addresses the compatibility issue in the code by defining the 'user-select' property without a vendor prefix, ensuring proper rendering in modern web browsers. I have also added a linear gradient background, aligned the text elements in the centre and modified the hover property to increase the visual appeal and interactivity of the to-do list, providing a more engaging user experience.
Please consider merging my inputs, thank you! :)

Fix 'user-select' Property Compatibility Issue & Updated CSS features

---

examples/menu-1.html

Fix the menu (navbar)
FIxes #27

fix: Fixed the Menu bar to  Update (menu-1.html)

---

examples/ScrollingText.html
examples/spinner.html

A animation of hot coffee using html and css

Hot coffee

---

examples/cube.html

#Fixed issue #158
https://github.com/you-dont-need/You-Dont-Need-JavaScript/assets/143418802/3c286774-356e-4fd8-9e5d-5d1d52c1658f

Added Simple Animation Using Pure CSS

---

examples/Moving-road-animation.html

Add Moving Road Animation in example folder.
issue #168 
Screenshort -

Add Moving Road Animation

---

examples/tabs-1.html

I have modified Tab1.html file in Examples for better UI .
I will continue to contribute to this repo , with core Website development components made using HTML5 and CSS.
Fixing Issue #166

modification to tab1.html for better UI

---

examples/FloatingImage.html
examples/coffeemachine.html
examples/openingenvelope.html

A image is floating animation using html and css

Floating Image

---

examples/openingenvelope.html

When we touch on the envelope the envelope opens up 
created by using html and css

Opening Envelope

---

examples/coffeemachine.html
examples/openingenvelope.html

When we touch on the button , Coffee is got serving>>
created using html and css

Coffee Machine

---

examples/neon-button.html

#Fixed issue #135
https://github.com/you-dont-need/You-Dont-Need-JavaScript/assets/143418802/c2e2f55e-8379-4b55-ace2-1df4b65e4db7

Added neon button animation

---

examples/author.html

adding a simple author page using html and simple css

#172 adding an author page

---

examples/alert.html
examples/road.html

#Fixed issue #19
https://github.com/you-dont-need/You-Dont-Need-JavaScript/assets/143418802/7156d723-9b98-4b74-af76-ba84dd8f5150

Added Alert messages that can be hidden on click

---

examples/Tubelight.html

Here's the demo...
https://github.com/you-dont-need/You-Dont-Need-JavaScript/assets/110279038/1138718b-b95d-4510-bd35-5fb3ee9b16f7

Added Tubelight Effect Editable Text

---

examples/flower-animation.html

flower animation using html, css

flower animation

---

examples/movinghand.html

This PR adds A moving hand animation using simple CSS

#195/Moving hand

---

examples/moving hand animation using css

Fixes #195 
Created a moving hand emoji animation using CSS.
Hope this solves the issue.
Looking forward for merging this PR.

Create moving hand animation using CSS

---

examples/ProgressBar.html

Here's the demo...
https://github.com/you-dont-need/You-Dont-Need-JavaScript/assets/110279038/19b43e13-75c3-4959-b62a-d5e572768fc7

Added Progress Bar

---

examples/scroll_button.html

#Fixed issue #10
https://github.com/you-dont-need/You-Dont-Need-JavaScript/assets/143418802/de6fb3d1-0d15-41f8-a9e1-089fa7781edc

Added button for modal scrolls page to top

---

simple animation using CSS

Creating a code for simple animation using CSS

Add code for Creating a simple animation using CSS

---

examples/BoxAnimation.html

This is a simple box-themed CSS animation with customizable text content.
1. Open `index.html` in a web browser.
2. Observe the box-themed CSS animation with your text content.
- Box-themed CSS animation.
- A customizable box with your own text content.
- Continuous rotation effect.
- HTML
- CSS

BoxAnimation

---

examples/WavyFooter.html

Here's the demo...
https://github.com/you-dont-need/You-Dont-Need-JavaScript/assets/110279038/74956cfe-d7c1-4a33-adac-f49bef2d12ba

Added Wavy Animated Footer

---

Neon Button

Fixes #135 
Created a neon button using HTML and CSS.
Hope this solves the issue.
Screen Recording:
https://github.com/you-dont-need/You-Dont-Need-JavaScript/assets/143169520/7578733a-1d23-44a4-8d99-67c77c8ae939
Looking forward for merging this PR.

Create Neon Button

---

examples/Animated-search-box.html

Added animated search box

---

examples/Ninja-Scroll-Background-Animation.html

Hello there Maintainer, I have finally added my animation to this repository....
Kindly check, review, and merge it 
Thank you 
Here's the demo

added Ninja-Scroll-Background-Animation

---

examples/animatedDarkCarousel.html

This is a simple HTML and CSS animation of a ping-pong ball moving back and forth. The animation has a dark theme and changes the color of the ball as it bounces.
You can customize the animation by modifying the HTML and CSS code. To change the animation duration or colors, you can adjust the values in the `pingpong` keyframes.

pingpongball

---

examples/AnimatedButtons.html

I added comments to the AnimatedButtons.html file to explain what happen in that code.

Added comments to the AnimatedButtons.html

---

.gitignore
index.html

in order to not have the 404 page reading on the GitHub pages I have added an index page that has most of the developed pages fixing issue #107

[FIX] - adding an index page to the GitHub pages

---

examples/animated_hover_rotate_effect.html
examples/neon_hover_effect.html

solved #158 
[screen-capture.webm](https://github.com/you-dont-need/You-Dont-Need-JavaScript/assets/93398177/f9e5633e-cd58-4619-817b-190bbdd18c5e)

Neon hover effect

---

examples/pure-css-float-labels.html

sovled #60 
https://github.com/you-dont-need/You-Dont-Need-JavaScript/assets/45191575/6898fb0b-edc3-4226-84de-f567088a549e
In this issue: we required only floating label css, so i've not focused on design form, I've just added css for label to design required result.

floating label pure css

---

examples/3d-hand-loader.html
examples/bmi.html

This is the output of the code.
[3d-hand_loader.webm](https://github.com/you-dont-need/You-Dont-Need-JavaScript/assets/115408327/9daabb80-567f-447e-b2e8-6b7d7214b9b1)

3d hand loader

---

CODE_OF_CONDUCT.md
README.MD

This PR does the following:
1. adds codeblock with syntax highlighting for shell commands in `CODE_OF_CONDUCT.md`
2. fixes styleguide
3. fixes spacings
4. rewrites the **Contributing** section in `README.md`

Update README.md and CODE_OF_CONDUCT.md

---

examples/eyeAnimation.html

EyeAnimation

---

examples/shake-button.html

I added comments to the html file shake-button.html for explain the code in it.

Added comments to shake-button.html

---

README.MD

Latest contribuors image visible in readme.md now

---

Author/Author-page.html
README.md

WHAT DOES THIS PR DO : 
This PR fixes Author image in author page

#261/author-img-fixed

---

Author/Author-page.html

add home page link at author's page 
ISSUE #276 
close #276 
merge this PR

Fix:add home page link at author's page

---

Author/styles.css

ISSUE #278 
close #278 
this color is better than black color and also a attractive 
check it and merge

Fix: change color of "Dynamic Quotes" #278 

---

Author/Author-page.html
Author/styles.css

Fixes #297 
* Corrected the concerned typo in "Author-page"
* Customized the button to blend well with the background

[fix]: Typo bug, [feature]: button customization in "Author-page"

---

examples/About.html

Just modified the about.html to a decent looking about section

Modified examples/About.html file: Good looking about section

---

Author/styles.css

ISSUE #305 
close #305 
change background image and front page of author page...check it and merge it

change background image and front page of author page

---

CONTRIBUTING.md

Hey there!
First, if you are reading this , you are amazing⭐
I'm Armaan and taking part in Hacktoberfest and Hacksquad, many folks were contributing to this repo, so I thought why not as well.
When I checked the "CONTRIBUTING.md", it looked amazing yet simple.
I thought why not level it up as well? 
So, I made "CONTRIBUTING.md" way better, precise, fun and emojified! 🔥
Since I'm not the owner/repo maintainer, there might be a few problems in that and I deeply apologise for that.
This pr is free for any edits/modifications.
Additional INFO: Starred⭐✔️
Thanks and regards,
Armaan.

updated CONTRIBUTING.md, made it way better, precise, fun and emojified!

---

examples/Rolling ball.html

adding Rolling Ball example using Pure css

Create Rolling ball.html

---

examples/slider.html
examples/tabs-1.html

I added comments to the slider.html to explain what happened in that.

Added comments to the slider.html

---

simple css design

this is the pic of my css design

Create simple css design

---

responsive_hamburger_navbar/index.html

Added a responsive Navbar with sidebar for smaller screens!!

Fix Issue #346

---

README.md

Hey i updated readme with my loader

Added my loader link in the readme

---

examples/loader.html

flip animated circle by using HTML and CSS. #158 
[screen-capture (2).webm](https://github.com/you-dont-need/You-Dont-Need-JavaScript/assets/45910254/e4bdb21e-32d6-4cc5-8d88-7007598cd386)

flip-animated circle

---

distorted-text-animation/distorted-text-anim.css
distorted-text-animation/distorted-text.html

Fixes #374 
Uses pure css to make a smooth and appealing distorting (vanishing) text animation
* New folder "distorted-text-animation"
* Contains html and css files
* Load the html page with live server to view the effect
https://github.com/you-dont-need/You-Dont-Need-JavaScript/assets/119743101/6ce53c52-d5ff-46e2-a6e0-2f7630440955
* Useful for making dynamic textual components
* Useful for enhancing user experience 
* Can increase user interaction time with website due to appealing text-style

[Feature]: Added distorted text animation using pure css

---

examples/ToDo.html

Add todo list

---

README.md

Remove double up of Carousel and remove the broken links.
Remove broken links in Animated Buttons.
Fixed a line styling error.
Please mark as hacktober-fest.

Update errors on readme.md 

---

Portfoliowebsite/port.css
Portfoliowebsite/port.html

I have added a sample portfolio website using HTML, CSS I have used typescript for dynamic text .. so that portfolio looks much better ...
This is the screenshot of the website

Added a sample portfolio  website

---

accordion/accordion-style.css
accordion/accordion.html

🚩Implemented professional looking UI design for accordion 
Fixes #403 
* Added a folder "accordion" in project repository
* Contains accordion.html file for icon rendering and adding elemental structures
* Contains accordion-style.css for UI and transition effects
* Load html page with live server or run locally to view webpage
Creation of a base template for accordion for personal portfolios, documentation UI and FAQ columns
https://github.com/you-dont-need/You-Dont-Need-JavaScript/assets/119743101/6cede0cb-1832-45b1-85c5-41ce4676d19d

[Feature]: Addition of aesthetic UI accordion design for payment gateway using pure CSS

---

examples/image-border-hover-effect.html

contribute in #158 image border hover effect
[screen-capture (2).webm](https://github.com/you-dont-need/You-Dont-Need-JavaScript/assets/93398177/c0b9b13d-433a-4f8f-bd9d-81ea66a7d8d0)
@aayush105 please check and merge

image-border-hover-effect

---

examples/profile-card-hover-effect.html

contribute in #158 profile card hover effect 
[screen-capture (3).webm](https://github.com/you-dont-need/You-Dont-Need-JavaScript/assets/93398177/405991f1-ff07-44a0-aec0-13ba95f17c15)
@aayush105  please review and merge

profile-card-hover-effect

---

examples/card-slide-hover-effect.html

contribute in #158 issue to create slide hover effect 
[screen-capture (4).webm](https://github.com/you-dont-need/You-Dont-Need-JavaScript/assets/93398177/c5e9f427-ccb5-43db-bfc3-39086d485c78)
@aayush105 please check it and merge

card-slide-hover-effect

---

Login_Page/style.css

Improve the responsiveness of the login form
- Added media queries to ensure the login form displays properly on devices with different screen size. 
- Adjusted the width and padding of the wrapper for smaller screens to improve user experience.
- output in a mobile device

Improve login page responsiveness

---

Cursor/index.html
Cursor/style.css

Issue #427 
Added Auto, Default, crosshair, wait, and text cursor types.

Added cursor types

---

Card1.html
card1.css
card2.css
card2.html

Added Profile Cards

---

index.html

@aayush105 I have added the Chatbot to the website for answering any queries. Kindly review this.

Chatbot Added

---

index.html

@aayush105 I have added the MultiLanguage Facility to the website. Kindly review this.

MultiLanguage Facility

---

Login/Signin.css
Login/Signin.html

Correctly linked the CSS file with HTML and positioned the Login box at center and made the page responsive. solved the issue #469
[Screencast from 2024-10-04 00-21-01.webm](https://github.com/user-attachments/assets/fcb51d8a-b137-48d9-b03d-e915a3340330)

Made the page responsive 

---

index.html

@aayush105 I have added the Toggle Functionality to the Main Page. Kindly review this.
https://github.com/user-attachments/assets/b935731a-13fd-4f45-a4ea-552acfb3aa46

Adding Toggle Functionality

---

Analog-clock/index.html

The hour, minute, and second divs are now siblings inside the clock div. This is the correct approach for styling and applying JavaScript in a typical analog clock scenario.

Update Separate div Elements for Clock Hands index.html

---

Analog-clock/index.css

Ensures the hour hand is behind the minute and second hands.

Update z-index  index.css

---

index.html

Reorganized and updated content and projects, improved layout, added categories for better user experience and made the landing page responsive.
- Reorganized content into categories: 3D and Animations, CSS Art, Layout and Components, Websites and Projects, Miscellaneous, Examples, V2, Misc, and Other
- Improved table layout for better readability
- Added new dark/light mode toggle button with better styling
- Added new "working" to various CSS examples and projects
- Improved responsive design for mobile devices
- ***Major Change:*** Added all the new projects recently merged to the repo.
Demo Image and Video:
https://github.com/user-attachments/assets/8f02b6f7-4d16-43b1-bb81-5b0825028fe8
Please review and let me know if any further changes are needed.

Updated landing page

---

index.html

Dear @aayush105 I have make certain changes in the font and the colour combinations to make it more appealing to a user. Kindly check the progress and guide me about the future changes (if applicable).
**BEFORE**
**AFTER**

Enhance the Landing Page

---

Captain America Shield/index.html
Captain America Shield/style.css

This pull request enhances the visual appeal of the Captain America Shield project by:
- added a feature to rotate the star of the shield on hovering
- added a feature to change the color of the shield from classic Red Blue to Winter Soldier theme
Demo Video:
https://github.com/user-attachments/assets/5b9bf8c6-7142-4710-80fb-e0211d20cd31
Screenshots:
If you find these changes effective please accept the pull request and also label it under Hacktoberfest

Updated Captain America Shield HTML and CSS

---

Author/Author-page.html
Author/styles.css

As mentioned in Issue #500 , the Authors page needed a refresh with a change of animations and change in text in layout.
Therefore, I have added a sliding transition onto the page, with the text and the button along with the bottom half of the page which includes the authors images and their quotes. The text layout of the quotes have also been given proper space so that they look presentable.
A screenshot added showing the transitioning effect.
[image](https://github.com/user-attachments/assets/c9277290-13de-4ec6-90bd-72794625b949)
[✅] I have performed a self-review of my code.
[✅] I ran the app and tested it locally to verify that it works as expected.
[✅] I have checked my code with an automatic accessibility tool and it shows no errors.
Kindly let me know if there's something I have to …

Adressing a Issue on the Author's Page

---

index.html

#547 i added a check box to ensure that when the check box is ticked it remains in the dark mode and otherwise light mode so it helps user to navigate between pages and stilll be in dark mode

solved the issue of black light persistence

---

Cards/flipping-card/index.html

This PR will add a flipping card upon hovering the card.
https://github.com/user-attachments/assets/78e16968-8fa9-4d47-bdda-034c70d227b2

feat: add flipping card on hover

---

index.html

Greetings @aayush105 I have previously added a real estate website to your repository so now I have made changes to showcase that website at your main website page. Kindly checkout the changes and make response to it.
Thank you!!!

Adding Website to main page

---

SolarSystem/style.css

I have added stars and also added css animation, the planets revolve around the sun in the orbit. They revolve around sun with also the moon revolve the earth.

Animated Solar system

---

Responsive navbar/index.html
index.html

Created a navbar with modern glow effect using tailwind css and css and added it to main index page.

Responsive glowing navbar

---

animation-box tutorial/keyframes.html
animation-box tutorial/readme.md

https://github.com/user-attachments/assets/cd6d968b-464c-4b54-b1f2-1ccf4c4da491

Animation box tutorial

---

Parallax_Effect/index.html
index.html

added parallax_effect in portfolio .

parallax_effect added

---

Animated Submit Button/index.css
Animated Submit Button/index.html

- Added a submit button, that animates on being clicked.
- A tick appears when it is clicked.
- HTML
- CSS

Animated Submit Button

---

Cube 360 view/My Project
Cube 360 view/click.html
Cube 360 view/styles.css

Created a 3d rotating animation using only html and css
https://github.com/user-attachments/assets/10b7cc77-2b5d-434b-9f4f-4e28c6aba3ed

360 degree animation of a cube

---

Light Bulb Animation/bulb.html

This pull request fix an attractive light bulb animation to the project, using HTML and embedded CSS. The main features of this update include:
- **Smooth on/off light bulb animation**: The animation toggles the light bulb between lit and unlit states with a smooth transition.
- **Minimalistic and clean design**: A sleek design that can integrate seamlessly into any webpage.
- **Cross-browser compatibility**: Ensures consistent behavior across modern web browsers.
- **Easy customization**: The CSS is well-commented for simple adjustments, including color changes and animation speed.
This addition enhances the visual appeal of the project, making it more engaging for users. Perfect for web projects or educational purposes. ✨

fix light bulb naiamtion 

---

Glassmorphism login page/index.html

Flexible Widths: Used relative widths (90%) for .box to make it responsive.
Max Width for Larger Screens: Added max-width: 400px to .box so it doesn’t stretch too wide on larger screens.
Flexbox Adjustments: Adjusted .sign and .login to be flexible within .slider for better handling on small screens.
Form Layout: Adjusted the .form-box elements to ensure they stay within the available width and align in a flexible grid.
Spacing Adjustments: Added margins and padding adjustments to improve layout on smaller screens.
Earlier:
Updated:

Fixed overlapping elements(while reducing window size)

---

Dancing Alphabets/Dancing Alphabets.html
Dancing Alphabets/readme.md

https://github.com/user-attachments/assets/190be865-0a73-4a3f-9682-9c3cea49d699

Dancing alphabets

---

Advanced Dancing Animation-tutorial/Advanced Dancing Animation.html
Advanced Dancing Animation-tutorial/readme.md

https://github.com/user-attachments/assets/6f3bd203-d48b-42c1-a80d-1687fdcf4607

Advanced dancing animation tutorial

---

Parallax Effect Scroll/Parralax.html

Fixes Issue: #637 
https://github.com/user-attachments/assets/f57213fe-ebe7-43ad-a7fb-dc1961d1886d
[✅] I have performed a self-review of my code.
[✅] I ran the app and tested it locally to verify that it works as expected.
[✅] I have checked my code with an automatic accessibility tool and it shows no errors.
Kindly let me know if there is something I have to change/adjust with the code! @aayush105

Parallax Scroll Effect

---

Animated Navigation Menu-tutorial/Animated Navigation Menu.html
Animated Navigation Menu-tutorial/readme.md

https://github.com/user-attachments/assets/da9f2496-5e63-4846-ab14-f1478118af8a

Hovering-navigation menu tutorial

---

Business-Card/index.html
Business-Card/styles.css

I changed the UI of the Business-Card

Modified Business-Card

---

circ.html
circular.html

A simple Circular Progressive bar

---

Top 10/3D Rotating Cube.html
Top 10/Glowing Orb with Rotating Rings.html
Top 10/Neon Cube Animation.html
Top 10/Neon Wireframe Cube.html
Top 10/Ripple Animation.html
Top 10/Text Reflection.html
Top 10/retro-flip-clock.html
Top 10/swirling-gradient-circle.html
Top 10/underwater-text.html

https://github.com/you-dont-need/You-Dont-Need-JavaScript/issues/686 solve 
https://github.com/user-attachments/assets/cec0fde6-c71e-4e5f-84fe-5f52181b7b61
https://github.com/user-attachments/assets/c07e3f38-916c-4a7e-8bd0-7bbaabfe0c00
https://github.com/user-attachments/assets/2263c33d-6a13-459d-8162-3b7bfa6239f3
https://github.com/user-attachments/assets/61700c1b-6637-44fc-abcb-e2f8ba03afed
https://github.com/user-attachments/assets/1100e126-958d-49e8-a295-fd2563033ea9
https://github.com/user-attachments/assets/a0c2ecf9-dc07-4f9c-8153-934484dc0d49
https://github.com/user-attachments/assets/ac703c90-bc88-448c-b11a-a5e7ba800f3f
https://github.com/user-attachments/assets/f2cf2d98-8d2b-4a01-8a6e-b7fdd23dd918
Rainbow Swirl Pulse
• Description: A dazzling rainbow loader with swirling …

ADD CSS Animation Oasis: A Collection of 10 Hypnotic and Interactive Visuals

---

Glassmorphism login page/index.html

#741 
fixed layout overflow issue and improved responsiveness — form now stays centered and scrolls properly on smaller screens, adjusted padding and spacing for cleaner alignment and better visual balance
before:
after:
https://github.com/user-attachments/assets/076ddb26-db84-4066-8bb1-b214ddf67488

B i  hover effects #741
